# Generated by Django 5.1.7 on 2025-04-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_adminwebuser_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
