# Generated by Django 5.1.7 on 2025-03-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTrigal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePlace', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumberUser', models.CharField(max_length=20, unique=True)),
                ('nameUser', models.CharField(max_length=40, null=True)),
                ('documentUser', models.CharField(max_length=20, null=True, unique=True)),
                ('experienceUser', models.TextField(default='...', max_length=400)),
                ('placeUser', models.TextField(max_length=60, null=True)),
                ('imageUser', models.ImageField(blank=True, null=True, upload_to='user_files/')),
                ('cvUser', models.FileField(blank=True, null=True, upload_to='user_files/')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('placeTrigal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messagewpp.placetrigal')),
            ],
        ),
    ]
