# Generated by Django 5.1.7 on 2025-03-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagewpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagewpp.placetrigal'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagewpp.placetrigal'),
        ),
    ]
