# Generated by Django 5.1.7 on 2025-04-07 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagewpp', '0002_messagetemplate_place_uploadedfile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='dateRequestUser',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
