# Generated by Django 5.1.7 on 2025-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagewpp', '0003_whatsappuser_daterequestuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='phoneNumberUser',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
